name: spotify_music_widget
description: A simple transparent widget to display information about the currently playing Spotify track.

publish_to: "none"
version: 2.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+2
  bitsdojo_window: ^0.1.1+1
  transparent_image: ^2.0.0
  window_manager: ^0.2.1
  keymap: ^0.0.81
  windows_taskbar: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
